In [1]:
import requests
import json
import pandas as pd
from pandas.io.json import json_normalize

In [2]:
# Retrieve data (updated daily)

# limit=0 to retrieve all available data, otherwise use limit=x where x=data points
btc_sent_url = 'https://api.alternative.me/fng/?limit=0'
btc_sent_raw = json.loads(requests.get(btc_sent_url).text)

In [3]:
# Create and clean DataFrame

# Normalise nested JSON
df_btc_sent = json_normalize(btc_sent_raw['data'])

# Deleting unused column
df_btc_sent.drop('time_until_update', axis=1, inplace=True)

# Convert timestamp to datetime
# add '.dt.normalize()' at the end to change all times to midnight
df_btc_sent['timestamp'] = pd.to_datetime(df_btc_sent['timestamp'], unit='s')

# Renaming columns
df_btc_sent.columns = ['date', 'btc_sent_value', 'btc_sent']

In [4]:
# Creating dummy variables for easier analysis
df_btc_sent = df_btc_sent.join(pd.get_dummies(df_btc_sent['btc_sent']))

In [5]:
df_btc_sent.head(20)

,date,btc_sent_value,btc_sent,Extreme Fear,Fear,Greed,Neutral
0,2019-03-14 04:00:00,55,Greed,0,0,1,0
1,2019-03-13 04:00:00,54,Neutral,0,0,0,1
2,2019-03-12 04:00:00,56,Greed,0,0,1,0
3,2019-03-11 04:00:00,56,Greed,0,0,1,0
4,2019-03-10 05:00:00,55,Greed,0,0,1,0
5,2019-03-09 05:00:00,55,Greed,0,0,1,0
6,2019-03-08 05:00:00,54,Neutral,0,0,0,1
7,2019-03-07 05:00:00,56,Greed,0,0,1,0
8,2019-03-06 05:00:00,42,Fear,0,1,0,0
9,2019-03-05 05:00:00,35,Fear,0,1,0,0
10,2019-03-04 05:00:00,36,Fear,0,1,0,0
11,2019-03-03 05:00:00,44,Fear,0,1,0,0
12,2019-03-02 05:00:00,41,Fear,0,1,0,0
13,2019-03-01 05:00:00,42,Fear,0,1,0,0
14,2019-02-28 05:00:00,39,Fear,0,1,0,0
15,2019-02-27 05:00:00,39,Fear,0,1,0,0
16,2019-02-26 05:00:00,40,Fear,0,1,0,0
17,2019-02-25 05:00:00,47,Neutral,0,0,0,1
18,2019-02-24 05:00:00,69,Greed,0,0,1,0
19,2019-02-23 05:00:00,63,Greed,0,0,1,0